[ALPS03958286] build: fix illegal character encoding
Fix clang build error:

error: illegal character encoding in string literal
[-Werror,-Winvalid-source-encodin[1

MTK-Commit-Id: 78f09c60aa5feb5fbace9467884cb9a4881e963f

Change-Id: Iab42e20dd51c438b4139b9bf1f796fd51accfe6b
CR-Id: ALPS03958286
Feature: [Module]Kernel Maintenance
Signed-off-by: Ethan Chang <ethan.chang@mediatek.com>
(cherry picked from commit d177d3a88794e69ac57d0a40154215c332d492f9)