[ALPS03958286] build: fix indirection of non-volatile null pointer
[Detail]
Fix the following build error:
error: indirection of non-volatile null pointer will be deleted,
not trap [-Werror,-Wnull-dereference]

MTK-Commit-Id: bebd96666680854f3206e4bc49302cf716fdda9c

Change-Id: Icaf4dabb25a77379d1e1d3d84876fb5c08754fc4
Signed-off-by: Ethan Chang <ethan.chang@mediatek.com>
CR-Id: ALPS03958286
Feature: Thermal Management
(cherry picked from commit e768573fa872121f5ac0bc238f0d37902929046b)